/* ============================================================
   On Device - the offline helper (service worker)

   Its only job is to keep a copy of this site's own files on your
   device so the site works with the internet switched off.

   It never touches your files, and it will not talk to any
   address other than this site's own. Requests to anywhere else
   are passed straight through untouched - and the Content
   Security Policy in every page refuses them anyway.

   The list below is generated by scripts/build-sw.mjs. Do not
   edit it by hand.
   ============================================================ */

/* --- BUILD:VERSION --- */
const VERSION = "0.1.0-fb0b490dcc";
/* --- END BUILD:VERSION --- */

const CACHE = `ondevice-${VERSION}`;

/* --- BUILD:PRECACHE --- */
const PRECACHE = [
  "./",
  "./.nojekyll",
  "./assets/css/base.css",
  "./assets/css/components.css",
  "./assets/css/tokens.css",
  "./assets/icons/favicon.svg",
  "./assets/icons/icon-180.png",
  "./assets/icons/icon-192.png",
  "./assets/icons/icon-256.png",
  "./assets/icons/icon-32.png",
  "./assets/icons/icon-512.png",
  "./assets/icons/icon-maskable-512.png",
  "./assets/icons/mask-icon.svg",
  "./assets/icons/social.png",
  "./assets/js/app.js",
  "./assets/js/colour.js",
  "./assets/js/defaults.js",
  "./assets/js/dropzone.js",
  "./assets/js/hash.js",
  "./assets/js/home.js",
  "./assets/js/i18n.js",
  "./assets/js/idb.js",
  "./assets/js/image/compose.js",
  "./assets/js/image/cutout.js",
  "./assets/js/image/decode.js",
  "./assets/js/image/exif.js",
  "./assets/js/image/obscure.js",
  "./assets/js/image/ops.js",
  "./assets/js/image/pipeline.js",
  "./assets/js/image/runner.js",
  "./assets/js/image/strip.js",
  "./assets/js/layout.js",
  "./assets/js/lock.js",
  "./assets/js/marker.js",
  "./assets/js/measure.js",
  "./assets/js/netguard.js",
  "./assets/js/page-credits.js",
  "./assets/js/page-home.js",
  "./assets/js/page-recipes.js",
  "./assets/js/page-roadmap.js",
  "./assets/js/page-settings.js",
  "./assets/js/page-static.js",
  "./assets/js/page-trust.js",
  "./assets/js/palette.js",
  "./assets/js/pdf-tool-page.js",
  "./assets/js/pdf/compress.js",
  "./assets/js/pdf/doc.js",
  "./assets/js/pdf/edit.js",
  "./assets/js/pdf/loader.js",
  "./assets/js/pdf/ocr.js",
  "./assets/js/pdf/password.js",
  "./assets/js/pdf/redact.js",
  "./assets/js/pdf/render.js",
  "./assets/js/pdf/stamp.js",
  "./assets/js/preboot.js",
  "./assets/js/qr-read.js",
  "./assets/js/qr.js",
  "./assets/js/queue.js",
  "./assets/js/recipes/names.js",
  "./assets/js/recipes/run.js",
  "./assets/js/recipes/steps.js",
  "./assets/js/recipes/store.js",
  "./assets/js/search-terms.js",
  "./assets/js/shortcuts.js",
  "./assets/js/sniff.js",
  "./assets/js/store.js",
  "./assets/js/strings/en.js",
  "./assets/js/strings/hi.js",
  "./assets/js/tool-page.js",
  "./assets/js/tools.js",
  "./assets/js/tools/background-remover.js",
  "./assets/js/tools/checksum.js",
  "./assets/js/tools/colour-palette.js",
  "./assets/js/tools/file-compare.js",
  "./assets/js/tools/file-lock.js",
  "./assets/js/tools/icon-generator.js",
  "./assets/js/tools/image-blur.js",
  "./assets/js/tools/image-combine.js",
  "./assets/js/tools/image-compress.js",
  "./assets/js/tools/image-convert.js",
  "./assets/js/tools/image-crop.js",
  "./assets/js/tools/image-metadata.js",
  "./assets/js/tools/image-resize.js",
  "./assets/js/tools/image-rotate.js",
  "./assets/js/tools/image-watermark.js",
  "./assets/js/tools/images-to-pdf.js",
  "./assets/js/tools/markdown.js",
  "./assets/js/tools/pdf-compress.js",
  "./assets/js/tools/pdf-extract-text.js",
  "./assets/js/tools/pdf-fill-sign.js",
  "./assets/js/tools/pdf-flatten.js",
  "./assets/js/tools/pdf-merge.js",
  "./assets/js/tools/pdf-metadata.js",
  "./assets/js/tools/pdf-nup.js",
  "./assets/js/tools/pdf-ocr.js",
  "./assets/js/tools/pdf-organise.js",
  "./assets/js/tools/pdf-page-numbers.js",
  "./assets/js/tools/pdf-password-add.js",
  "./assets/js/tools/pdf-password-remove.js",
  "./assets/js/tools/pdf-redact.js",
  "./assets/js/tools/pdf-rotate-crop.js",
  "./assets/js/tools/pdf-split.js",
  "./assets/js/tools/pdf-to-images.js",
  "./assets/js/tools/pdf-watermark.js",
  "./assets/js/tools/qr-generate.js",
  "./assets/js/tools/qr-read.js",
  "./assets/js/tools/screenshot-polish.js",
  "./assets/js/tools/spreadsheet.js",
  "./assets/js/tools/text-workbench.js",
  "./assets/js/tools/zip.js",
  "./assets/js/tray.js",
  "./assets/js/ui.js",
  "./assets/js/workers/image-worker.js",
  "./assets/js/workspace.js",
  "./credits.html",
  "./help.html",
  "./index.html",
  "./manifest.webmanifest",
  "./privacy.html",
  "./recipes.html",
  "./roadmap.html",
  "./settings.html",
  "./tools/background-remover.html",
  "./tools/checksum.html",
  "./tools/colour-palette.html",
  "./tools/file-compare.html",
  "./tools/file-lock.html",
  "./tools/icon-generator.html",
  "./tools/image-blur.html",
  "./tools/image-combine.html",
  "./tools/image-compress.html",
  "./tools/image-convert.html",
  "./tools/image-crop.html",
  "./tools/image-metadata.html",
  "./tools/image-resize.html",
  "./tools/image-rotate.html",
  "./tools/image-watermark.html",
  "./tools/images-to-pdf.html",
  "./tools/markdown.html",
  "./tools/pdf-compress.html",
  "./tools/pdf-extract-text.html",
  "./tools/pdf-fill-sign.html",
  "./tools/pdf-flatten.html",
  "./tools/pdf-merge.html",
  "./tools/pdf-metadata.html",
  "./tools/pdf-nup.html",
  "./tools/pdf-ocr.html",
  "./tools/pdf-organise.html",
  "./tools/pdf-page-numbers.html",
  "./tools/pdf-password-add.html",
  "./tools/pdf-password-remove.html",
  "./tools/pdf-redact.html",
  "./tools/pdf-rotate-crop.html",
  "./tools/pdf-split.html",
  "./tools/pdf-to-images.html",
  "./tools/pdf-watermark.html",
  "./tools/qr-generate.html",
  "./tools/qr-read.html",
  "./tools/screenshot-polish.html",
  "./tools/spreadsheet.html",
  "./tools/text-workbench.html",
  "./tools/zip.html",
  "./trust.html"
];
/* --- END BUILD:PRECACHE --- */

/* ---- Install: save every file ---------------------------- */
self.addEventListener("install", (event) => {
  event.waitUntil(
    (async () => {
      const cache = await caches.open(CACHE);
      /* Added one at a time so a single missing file does not
         silently abandon the whole cache. Anything that fails is
         reported in the console rather than hidden. */
      const failures = [];
      await Promise.all(
        PRECACHE.map(async (url) => {
          try {
            const response = await fetch(url, { cache: "reload" });
            if (!response.ok) throw new Error(`HTTP ${response.status}`);
            await cache.put(url, response);
          } catch (err) {
            failures.push({ url, message: err && err.message ? err.message : String(err) });
          }
        })
      );
      if (failures.length) {
        console.error("[On Device] These files could not be saved for offline use:", failures);
      }
      /* Take over as soon as possible so the first visit is already
         offline-capable. */
      await self.skipWaiting();
    })()
  );
});

/* ---- Activate: drop older versions ----------------------- */
self.addEventListener("activate", (event) => {
  event.waitUntil(
    (async () => {
      const names = await caches.keys();
      await Promise.all(
        names
          .filter((name) => name.startsWith("ondevice-") && name !== CACHE)
          .map((name) => caches.delete(name))
      );
      await self.clients.claim();
    })()
  );
});

/* ---- Fetch: our own files, from the cache first ---------- */
self.addEventListener("fetch", (event) => {
  const request = event.request;

  /* Only ever GET, and only ever this site. Anything else is left
     completely alone. */
  if (request.method !== "GET") return;

  let url;
  try {
    url = new URL(request.url);
  } catch (err) {
    return;
  }
  if (url.origin !== self.location.origin) return;

  event.respondWith(
    (async () => {
      const cached = await caches.match(request, { ignoreSearch: true });
      if (cached) return cached;

      try {
        const response = await fetch(request);
        /* Save anything successful for next time, so a tool's large
           module is only ever downloaded once. */
        if (response && response.ok && response.type === "basic") {
          const cache = await caches.open(CACHE);
          cache.put(request, response.clone());
        }
        return response;
      } catch (err) {
        /* Offline and not cached. For a page request, show the
           homepage, which is cached, rather than a browser error. */
        if (request.mode === "navigate") {
          const fallback = await caches.match("./index.html");
          if (fallback) return fallback;
        }
        return new Response(
          "This part of On Device is not saved on your device yet, and there is no " +
          "connection to fetch it with. Reconnect once and it will be saved for good.",
          { status: 503, headers: { "Content-Type": "text/plain; charset=utf-8" } }
        );
      }
    })()
  );
});

/* ---- Let a page tell us to activate immediately ---------- */
self.addEventListener("message", (event) => {
  if (event.data && event.data.type === "SKIP_WAITING") {
    self.skipWaiting();
  }
});
